---
# tasks file for lighthouse-role
- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release.noarch
    state: latest
- name: Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start-nginx
- name: Create general config NGINX
  become: true
  template:
    src: "template/nging.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0755
  notify: reload-nginx
  tags: install nginx
- name: Install dependencies lighthouse
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Copy from git lighthouse
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
- name: Create lighthouse config
  become: true
  template:
    src: "template/lighthouse.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: 0644
  notify: reload-nginx
  tags: install lighthouse